name: qr_code_tools
description: The Flutter plugin for iOS and Android to decoding QR codes.
version: 0.1.2
homepage: https://github.com/AifeiI/qr_code_tools

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.aifeii.qrcode.tools
        pluginClass: QrCodeToolsPlugin
      ios:
        pluginClass: QrCodeToolsPlugin